### ISSUE TITLE
Error in paths, locs in predict.py 

### ISSUE THREAD

**Issue by Noy987** [ciampluca/counting_perineuronal_nets#6]
Seems like I am not getting the needed values in paths, locs - how do i fix that? 
Could that be the reason that my output file "localizations.csv" is empty?

I ran this command:
python predict.py pnn_v2_fasterrcnn_640/ -r pnn_v2_scoring_rank_learning/  "C:\Users\NoyAzar\Desktop\Project\Rotems files\batch_1\slice 2\slice2-pv_downsized.png"

![Screenshot 2024-02-13 185822](https://github.com/ciampluca/counting_perineuronal_nets/assets/154227249/45d1b78e-9107-4219-9013-32bc6038dfbc)

Would love for some help, thanks!

**Comment by fabiocarrara** [comment]
Hi @Noy987 ,
The command in the screenshot does not match the one you wrote about.
Do you get the same error with your command?
However, it seems like an error in providing the correct path/names to the input images (in the screenshot, it is probably searching for TIFF images in the repo folder and not finding anything).
Can you try moving one input png image in the repo folder and run the command on the screenshot with `*.png` instead of `my_images_*.tiff`?

**Comment by Noy987** [comment]
Yes, sorry, you are right, here is the correct screenshot:

![image](https://github.com/ciampluca/counting_perineuronal_nets/assets/154227249/3e8595fc-7392-4fa8-9ecc-007cb413be5d)

**Comment by fabiocarrara** [comment]
It may be that the network has not found anything in the first detection step. What is the content of `localization.csv`?

**Comment by Noy987** [comment]
Got it to work, thanks!
